# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from GetAcl import *
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        MainWindow.setWindowTitle("PermissionTools(GetACL)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseButton.setGeometry(QtCore.QRect(510, 170, 111, 31))
        self.BrowseButton.setObjectName("BrowseButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 170, 411, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.PathLabel = QtWidgets.QLabel(self.centralwidget)
        self.PathLabel.setGeometry(QtCore.QRect(10, 170, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PathLabel.sizePolicy().hasHeightForWidth())
        self.PathLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.PathLabel.setFont(font)
        self.PathLabel.setObjectName("PathLabel")
        self.WelcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.WelcomeLabel.setGeometry(QtCore.QRect(0, 20, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.WelcomeLabel.setFont(font)
        self.WelcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.WelcomeLabel.setObjectName("WelcomeLabel")
        self.PresentedLabel = QtWidgets.QLabel(self.centralwidget)
        self.PresentedLabel.setGeometry(QtCore.QRect(510, 460, 121, 20))
        self.PresentedLabel.setObjectName("PresentedLabel")
        self.UserLabel = QtWidgets.QLabel(self.centralwidget)
        self.UserLabel.setGeometry(QtCore.QRect(10, 250, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserLabel.sizePolicy().hasHeightForWidth())
        self.UserLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.UserLabel.setFont(font)
        self.UserLabel.setObjectName("UserLabel")
        self.StartPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartPushButton.setGeometry(QtCore.QRect(510, 210, 111, 31))
        self.StartPushButton.setObjectName("ChangePushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 70, 371, 71))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(90, 251, 531, 211))
        self.textBrowser.setObjectName("textBrowser")
        self.DepthComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DepthComboBox.setGeometry(QtCore.QRect(90, 210, 411, 31))
        self.DepthComboBox.setObjectName("DepthComboBox")
        self.DepthLabel = QtWidgets.QLabel(self.centralwidget)
        self.DepthLabel.setGeometry(QtCore.QRect(10, 210, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DepthLabel.sizePolicy().hasHeightForWidth())
        self.DepthLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.DepthLabel.setFont(font)
        self.DepthLabel.setObjectName("DepthLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        ###############################################
        self.BrowseButton.clicked.connect(self.choose_directory)
        self.StartPushButton.clicked.connect(self.start_job)
        ###############################################
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def choose_directory(self):
        input_dir = QFileDialog.getExistingDirectory(None, 'Select a folder' )
        self.lineEdit.setText(input_dir)


    def start_job(self):
        if self.lineEdit.text() != "" :
            self.textBrowser.setText(get_acl(self.lineEdit.text() , int(self.DepthComboBox.currentText())))
        else :
            self.textBrowser.setText("Error : Select a Path!")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        
        ##############################################
        self.DepthComboBox.addItem("1")
        self.DepthComboBox.addItem("2")
        self.DepthComboBox.addItem("3")
        ##############################################



        self.BrowseButton.setText(_translate("MainWindow", "Browse"))
        self.PathLabel.setText(_translate("MainWindow", "Path :"))
        self.WelcomeLabel.setText(_translate("MainWindow", "Wellcome to Permission Tools!"))
        self.PresentedLabel.setText(_translate("MainWindow", "Presented By Ganjiid"))
        self.UserLabel.setText(_translate("MainWindow", "Report :"))
        self.StartPushButton.setText(_translate("MainWindow", "Change"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>HeyThere ! </p><p>This is a tool for getting a list of users with access permission</p><p>for a path which you choose . </p></body></html>"))
        self.DepthLabel.setText(_translate("MainWindow", "Depth :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
